export const dataTest = {
  success: true,
  message: 'Thành công',
  code: 0,
  data: [
    {
      id: 244,
      parentId: null,
      name: 'Thông tin cơ bản',
      sortOrder: 1,
      typeEditGroup: 1,
      groupType: 1,
      tableName: 'Employee',
      customConfig: '{"IsVerticalTab": true}',
      subsystemCode: 'Employee',
      note: '',
      isVisible: false,
      isTypeForm: false,
      isViewWhenAdd: true,
      isSystem: false,
      isExpand: true,
      groupFieldConfigs: [],
    },
    {
      id: 245,
      parentId: 244,
      name: 'Thông tin chung',
      sortOrder: 1,
      typeEditGroup: 1,
      groupType: 1,
      tableName: 'Employee',
      customConfig: '{"IsVerticalTab": true}',
      subsystemCode: 'Employee',
      note: '',
      isVisible: false,
      isTypeForm: false,
      isViewWhenAdd: true,
      isSystem: false,
      isExpand: true,
      groupFieldConfigs: [
        {
          id: 1540,
          groupConfigId: 245,
          typeControl: 1,
          sortOrder: 1,
          customConfig: '{"Maxlength": 50, "IsAutoCode": true}',
          rowIndex: 1,
          columnIndex: 1,
          defaultValue: '',
          subsystemCode: 'Employee',
          label: 'Mã nhân viên',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'EmployeeCode',
          tableNameSource: null,
          fieldNameSource: null,
          displayFieldSource: null,
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1541,
          groupConfigId: 245,
          typeControl: 0,
          sortOrder: 2,
          customConfig: '{"IsMergeEN": true, "Maxlength": 150}',
          rowIndex: 2,
          columnIndex: 1,
          defaultValue: '',
          subsystemCode: 'Employee',
          label: 'Họ và đệm',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'FirstName',
          tableNameSource: null,
          fieldNameSource: null,
          displayFieldSource: null,
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1542,
          groupConfigId: 245,
          typeControl: 0,
          sortOrder: 3,
          customConfig: '{"Maxlength": 255}',
          rowIndex: 3,
          columnIndex: 1,
          defaultValue: '',
          subsystemCode: 'Employee',
          label: 'Nguyên quán',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'HomeLand',
          tableNameSource: null,
          fieldNameSource: null,
          displayFieldSource: null,
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1543,
          groupConfigId: 245,
          typeControl: 0,
          sortOrder: 4,
          customConfig: '{"IsMergeEN": true, "Maxlength": 100}',
          rowIndex: 4,
          columnIndex: 1,
          defaultValue: '',
          subsystemCode: 'Employee',
          label: 'Tên',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'LastName',
          tableNameSource: null,
          fieldNameSource: null,
          displayFieldSource: null,
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1544,
          groupConfigId: 245,
          typeControl: 1,
          sortOrder: 5,
          customConfig:
            '{"IsMergeEN": true, "Maxlength": 255, "FormulaConfig": {"Type": 1, "Content": "${FirstName} + \' \' +${LastName}"}}',
          rowIndex: 5,
          columnIndex: 1,
          defaultValue: '',
          subsystemCode: 'Employee',
          label: 'Họ và tên',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'FullName',
          tableNameSource: null,
          fieldNameSource: null,
          displayFieldSource: null,
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: true,
        },
        {
          id: 1545,
          groupConfigId: 245,
          typeControl: 3,
          pickerData: [{}],
          sortOrder: 6,
          customConfig: '{"IsMergeEN": true, "Maxlength": 15}',
          rowIndex: 6,
          columnIndex: 1,
          defaultValue: '',
          subsystemCode: 'Employee',
          label: 'Giới tính',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'GenderID',
          tableNameSource: 'PickList',
          fieldNameSource: 'PickListID',
          displayFieldSource: 'PickListID',
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1546,
          groupConfigId: 245,
          typeControl: 0,
          sortOrder: 7,
          customConfig: '{"Maxlength": 255}',
          rowIndex: 7,
          columnIndex: 1,
          defaultValue: '',
          subsystemCode: 'Employee',
          label: 'Nơi sinh',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'BirthPlace',
          tableNameSource: null,
          fieldNameSource: null,
          displayFieldSource: null,
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1547,
          groupConfigId: 245,
          typeControl: 1,
          sortOrder: 2,
          customConfig: null,
          rowIndex: 2,
          columnIndex: 2,
          defaultValue: '',
          subsystemCode: 'Employee',
          label: 'hhh',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'GFN0000151CustomEmployee',
          tableNameSource: null,
          fieldNameSource: null,
          displayFieldSource: null,
          isDisable: false,
          isUse: false,
          isCustom: true,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1548,
          groupConfigId: 245,
          typeControl: 3,
          pickerData: [{}],
          sortOrder: 3,
          customConfig:
            '{"IsMergeEN": true, "Maxlength": 255, "PopupType": 4, "IsDynamicCombobox": true}',
          rowIndex: 3,
          columnIndex: 2,
          defaultValue: '',
          subsystemCode: 'Employee',
          label: 'Tình trạng hôn nhân',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'MaritalStatusID',
          tableNameSource: 'PickList',
          fieldNameSource: 'PickListID',
          displayFieldSource: 'PickListID',
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1549,
          groupConfigId: 245,
          typeControl: 0,
          sortOrder: 4,
          customConfig: '{"Maxlength": 20, "WarningCode": ["DulicateData"]}',
          rowIndex: 4,
          columnIndex: 2,
          defaultValue: '',
          subsystemCode: 'Employee',
          label: 'MST cá nhân',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'PersonalTaxCode',
          tableNameSource: null,
          fieldNameSource: null,
          displayFieldSource: null,
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1550,
          groupConfigId: 245,
          typeControl: 3,
          pickerData: [{}],
          sortOrder: 5,
          customConfig:
            '{"IsMergeEN": true, "Maxlength": 255, "PopupType": 4, "IsDynamicCombobox": true}',
          rowIndex: 5,
          columnIndex: 2,
          defaultValue: '',
          subsystemCode: 'Employee',
          label: 'TP bản thân',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'PersonalClassBackgroundID',
          tableNameSource: 'PickList',
          fieldNameSource: 'PickListID',
          displayFieldSource: 'PickListID',
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1551,
          groupConfigId: 245,
          typeControl: 3,
          pickerData: [{}],
          sortOrder: 6,
          customConfig: '{"Maxlength": 255}',
          rowIndex: 6,
          columnIndex: 2,
          defaultValue: '',
          subsystemCode: 'Employee',
          label: 'Dân tộc',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'EthnicID',
          tableNameSource: 'PickList',
          fieldNameSource: 'PickListID',
          displayFieldSource: 'PickListID',
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1552,
          groupConfigId: 245,
          typeControl: 3,
          pickerData: [{}],
          sortOrder: 7,
          customConfig:
            '{"IsMergeEN": true, "Maxlength": 255, "PopupType": 4, "IsDynamicCombobox": true}',
          rowIndex: 7,
          columnIndex: 2,
          defaultValue: '',
          subsystemCode: 'Employee',
          label: 'Tôn giáo',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'ReligionID',
          tableNameSource: 'PickList',
          fieldNameSource: 'PickListID',
          displayFieldSource: 'PickListID',
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1553,
          groupConfigId: 245,
          typeControl: 3,
          pickerData: [{}],
          sortOrder: 8,
          customConfig:
            '{"IsMergeEN": true, "Maxlength": 255, "PopupType": 4, "IsDynamicCombobox": true}',
          rowIndex: 8,
          columnIndex: 2,
          defaultValue: '',
          subsystemCode: 'Employee',
          label: 'TP gia đình',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'FamilyClassBackgroundID',
          tableNameSource: 'PickList',
          fieldNameSource: 'PickListID',
          displayFieldSource: 'PickListID',
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1554,
          groupConfigId: 245,
          typeControl: 0,
          sortOrder: 8,
          customConfig: null,
          rowIndex: 8,
          columnIndex: 2,
          defaultValue: '',
          subsystemCode: 'Employee',
          label: 'Tên gọi khác',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'OtherName',
          tableNameSource: null,
          fieldNameSource: null,
          displayFieldSource: null,
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1555,
          groupConfigId: 245,
          typeControl: 5,
          sortOrder: 9,
          customConfig: '{"IsMergeEN": true}',
          rowIndex: 9,
          columnIndex: 2,
          defaultValue: '',
          subsystemCode: 'Employee',
          label: 'Ngày sinh',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'BirthDay',
          tableNameSource: null,
          fieldNameSource: null,
          displayFieldSource: null,
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1556,
          groupConfigId: 245,
          typeControl: 3,
          pickerData: [{}],
          sortOrder: 9,
          customConfig:
            '{"CacheName": "Nation", "IsMergeEN": true, "Maxlength": 255, "IsTranslateAddress": true}',
          rowIndex: 9,
          columnIndex: 2,
          defaultValue: '',
          subsystemCode: 'Employee',
          label: 'Quốc tịch',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'NationalityID',
          tableNameSource: null,
          fieldNameSource: 'LocationID',
          displayFieldSource: 'LocationID',
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1557,
          groupConfigId: 245,
          typeControl: 1,
          sortOrder: 10,
          customConfig: null,
          rowIndex: 10,
          columnIndex: 2,
          defaultValue: '',
          subsystemCode: 'Employee',
          label: 'Một dòng',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'GFN0000153CustomEmployee',
          tableNameSource: null,
          fieldNameSource: null,
          displayFieldSource: null,
          isDisable: false,
          isUse: true,
          isCustom: true,
          isSystem: false,
          isReadOnly: false,
        },
      ],
    },
  ],
};

import apiClient from './apiClient';

export const getData = async (layout: string) => {
  try {
    const layout = 'profile';
    // Giả sử bạn có một API endpoint để lấy dữ liệu dựa trên layout
    const response = await apiClient.post(
      `ConfigLayout/setting-layout?layout=${layout}`,
    );
    const data = await response.data;
    return data;
  } catch (error) {
    console.error('Error fetching data:', error);
    throw error;
  }
};
