export const dataTest = {
  success: true,
  message: 'Thành công',
  code: 0,
  pageData: [
    {
      id: 301,
      parentId: null,
      name: 'Thông tin cơ bản',
      sortOrder: 1,
      typeEditGroup: 1,
      groupType: 1,
      tableName: 'Employee',
      customConfig: '{"IsVerticalTab": true}',
      subsystemCode: 'Employee',
      note: '',
      isVisible: false,
      isTypeForm: false,
      isViewWhenAdd: true,
      isSystem: false,
      isExpand: true,
      groupFieldConfigs: [],
    },
    {
      id: 302,
      parentId: 301,
      name: 'Thông tin chung',
      sortOrder: 1,
      typeEditGroup: 1,
      groupType: 1,
      tableName: 'Employee',
      customConfig: '{"IsVerticalTab": true}',
      subsystemCode: 'Employee',
      note: '',
      isVisible: false,
      isTypeForm: false,
      isViewWhenAdd: true,
      isSystem: false,
      isExpand: true,
      groupFieldConfigs: [
        {
          id: 1923,
          groupConfigId: 302,
          typeControl: 'TextOne',
          pickerData: [{}],
          sortOrder: 1,
          customConfig: '{"Maxlength": 50, "IsAutoCode": true}',
          rowIndex: 1,
          columnIndex: 1,
          defaultValue: null,
          subsystemCode: 'Employee',
          label: 'Mã nhân viên',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'employeeCode',
          tableNameSource: null,
          fieldNameSource: null,
          displayFieldSource: null,
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1924,
          groupConfigId: 302,
          typeControl: 'TextOne',
          pickerData: [{}],
          sortOrder: 2,
          customConfig: '{"IsMergeEN": true, "Maxlength": 150}',
          rowIndex: 2,
          columnIndex: 1,
          defaultValue: null,
          subsystemCode: 'Employee',
          label: 'Họ và đệm',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'firstName',
          tableNameSource: null,
          fieldNameSource: null,
          displayFieldSource: null,
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1925,
          groupConfigId: 302,
          typeControl: 'TextOne',
          pickerData: [{}],
          sortOrder: 3,
          customConfig: '{"Maxlength": 255}',
          rowIndex: 3,
          columnIndex: 1,
          defaultValue: null,
          subsystemCode: 'Employee',
          label: 'Nguyên quán',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'homeLand',
          tableNameSource: null,
          fieldNameSource: null,
          displayFieldSource: null,
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1926,
          groupConfigId: 302,
          typeControl: 'TextOne',
          pickerData: [{}],
          sortOrder: 4,
          customConfig: '{"IsMergeEN": true, "Maxlength": 100}',
          rowIndex: 4,
          columnIndex: 1,
          defaultValue: null,
          subsystemCode: 'Employee',
          label: 'Tên',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'lastName',
          tableNameSource: null,
          fieldNameSource: null,
          displayFieldSource: null,
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1927,
          groupConfigId: 302,
          typeControl: 'TextOne',
          pickerData: [{}],
          sortOrder: 5,
          customConfig:
            '{"IsMergeEN": true, "Maxlength": 255, "FormulaConfig": {"Type": 1, "Content": "${FirstName} + \' \' +${LastName}"}}',
          rowIndex: 5,
          columnIndex: 1,
          defaultValue: null,
          subsystemCode: 'Employee',
          label: 'Họ và tên',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'fullName',
          tableNameSource: null,
          fieldNameSource: null,
          displayFieldSource: null,
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: true,
        },
        {
          id: 1928,
          groupConfigId: 302,
          typeControl: 'SelectOne',
          sortOrder: 6,
          customConfig: '{"IsMergeEN": true, "Maxlength": 15}',
          rowIndex: 6,
          columnIndex: 1,
          defaultValue: null,
          subsystemCode: 'Employee',
          label: 'Giới tính',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'genderID',
          tableNameSource: 'PickList',
          fieldNameSource: 'PickListID',
          displayFieldSource: 'PickListID',
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1929,
          groupConfigId: 302,
          typeControl: 'SelectOne',
          pickerData: [{}],
          sortOrder: 7,
          customConfig: '{"Maxlength": 255}',
          rowIndex: 7,
          columnIndex: 1,
          defaultValue: null,
          subsystemCode: 'Employee',
          label: 'Nơi sinh',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'birthPlace',
          tableNameSource: null,
          fieldNameSource: null,
          displayFieldSource: null,
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1930,
          groupConfigId: 302,
          typeControl: 'SelectMany',
          pickerData: [{}],
          sortOrder: 2,
          customConfig: null,
          rowIndex: 2,
          columnIndex: 2,
          defaultValue: null,
          subsystemCode: 'Employee',
          label: 'hhh',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'gFN0000151CustomEmployee',
          tableNameSource: null,
          fieldNameSource: null,
          displayFieldSource: null,
          isDisable: false,
          isUse: false,
          isCustom: true,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1931,
          groupConfigId: 302,
          typeControl: 'SelectOne',
          sortOrder: 3,
          customConfig:
            '{"IsMergeEN": true, "Maxlength": 255, "PopupType": 4, "IsDynamicCombobox": true}',
          rowIndex: 3,
          columnIndex: 2,
          defaultValue: null,
          subsystemCode: 'Employee',
          label: 'Tình trạng hôn nhân',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'maritalStatusID',
          tableNameSource: 'PickList',
          fieldNameSource: 'PickListID',
          displayFieldSource: 'PickListID',
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1932,
          groupConfigId: 302,
          typeControl: 'TextOne',
          pickerData: [{}],
          sortOrder: 4,
          customConfig: '{"Maxlength": 20, "WarningCode": ["DulicateData"]}',
          rowIndex: 4,
          columnIndex: 2,
          defaultValue: null,
          subsystemCode: 'Employee',
          label: 'MST cá nhân',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'personalTaxCode',
          tableNameSource: null,
          fieldNameSource: null,
          displayFieldSource: null,
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1933,
          groupConfigId: 302,
          typeControl: 'TextOne',
          sortOrder: 5,
          customConfig:
            '{"IsMergeEN": true, "Maxlength": 255, "PopupType": 4, "IsDynamicCombobox": true}',
          rowIndex: 5,
          columnIndex: 2,
          defaultValue: null,
          subsystemCode: 'Employee',
          label: 'TP bản thân',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'personalClassBackgroundID',
          tableNameSource: 'PickList',
          fieldNameSource: 'PickListID',
          displayFieldSource: 'PickListID',
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1934,
          groupConfigId: 302,
          typeControl: 'SelectOne',
          sortOrder: 6,
          customConfig: '{"Maxlength": 255}',
          rowIndex: 6,
          columnIndex: 2,
          defaultValue: '{"EthnicID": 1, "EthnicName": "Kinh"}',
          subsystemCode: 'Employee',
          label: 'Dân tộc',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'ethnicID',
          tableNameSource: 'PickList',
          fieldNameSource: 'PickListID',
          displayFieldSource: 'PickListID',
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1935,
          groupConfigId: 302,
          typeControl: 'SelectOne',
          sortOrder: 7,
          customConfig:
            '{"IsMergeEN": true, "Maxlength": 255, "PopupType": 4, "IsDynamicCombobox": true}',
          rowIndex: 7,
          columnIndex: 2,
          defaultValue: '{"ReligionID": 1, "ReligionName": "Không"}',
          subsystemCode: 'Employee',
          label: 'Tôn giáo',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'religionID',
          tableNameSource: 'PickList',
          fieldNameSource: 'PickListID',
          displayFieldSource: 'PickListID',
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1936,
          groupConfigId: 302,
          typeControl: 'TextOne',
          sortOrder: 8,
          customConfig:
            '{"IsMergeEN": true, "Maxlength": 255, "PopupType": 4, "IsDynamicCombobox": true}',
          rowIndex: 8,
          columnIndex: 2,
          defaultValue: null,
          subsystemCode: 'Employee',
          label: 'TP gia đình',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'familyClassBackgroundID',
          tableNameSource: 'PickList',
          fieldNameSource: 'PickListID',
          displayFieldSource: 'PickListID',
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1937,
          groupConfigId: 302,
          typeControl: 'TextOne',
          pickerData: [{}],
          sortOrder: 8,
          customConfig: null,
          rowIndex: 8,
          columnIndex: 2,
          defaultValue: null,
          subsystemCode: 'Employee',
          label: 'Tên gọi khác',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'otherName',
          tableNameSource: null,
          fieldNameSource: null,
          displayFieldSource: null,
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1938,
          groupConfigId: 302,
          typeControl: 'DateTime',
          sortOrder: 9,
          customConfig: '{"IsMergeEN": true}',
          rowIndex: 9,
          columnIndex: 2,
          defaultValue: null,
          subsystemCode: 'Employee',
          label: 'Ngày sinh',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'birthDay',
          tableNameSource: null,
          fieldNameSource: null,
          displayFieldSource: null,
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1939,
          groupConfigId: 302,
          typeControl: 'SelectOne',
          sortOrder: 9,
          customConfig:
            '{"CacheName": "Nation", "IsMergeEN": true, "Maxlength": 255, "IsTranslateAddress": true}',
          rowIndex: 9,
          columnIndex: 2,
          defaultValue:
            '{"NationalityID": "VN", "NationalityName": "Việt Nam"}',
          subsystemCode: 'Employee',
          label: 'Quốc tịch',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'nationalityID',
          tableNameSource: null,
          fieldNameSource: 'LocationID',
          displayFieldSource: 'LocationID',
          isDisable: false,
          isUse: true,
          isCustom: false,
          isSystem: false,
          isReadOnly: false,
        },
        {
          id: 1940,
          groupConfigId: 302,
          typeControl: 'TextOne',
          pickerData: [{}],
          sortOrder: 10,
          customConfig: null,
          rowIndex: 10,
          columnIndex: 2,
          defaultValue: null,
          subsystemCode: 'Employee',
          label: 'Một dòng',
          value: null,
          valueText: '',
          tableName: 'Employee',
          fieldName: 'gFN0000153CustomEmployee',
          tableNameSource: null,
          fieldNameSource: null,
          displayFieldSource: null,
          isDisable: false,
          isUse: true,
          isCustom: true,
          isSystem: false,
          isReadOnly: false,
        },
      ],
    },
  ],
  page: 0,
  pageSize: 0,
  total: 0,
};

import apiClient from './apiClient';

export const getData = async (layout: string) => {
  try {
    const layout = 'profile';
    // Giả sử bạn có một API endpoint để lấy dữ liệu dựa trên layout
    const response = await apiClient.post(
      `ConfigLayout/setting-layout?layout=${layout}`,
    );
    const data = await response.data;
    return data;
  } catch (error) {
    console.error('Error fetching data:', error);
    throw error;
  }
};

export const getEmployee = async (id: number) => {
  try {
    const response = await apiClient.get(`/Employee/${id}`);
    return response.data;
  } catch (error) {
    console.error('Error fetching employee:', error);
    throw error;
  }
};
