export const groupConfig = {
  GroupConfigID: 11514,
  GroupConfigName: 'Thông tin chung',
  GroupConfigName_EN: 'General information',
  GroupConfigCode: 'CommonInfo',
  LayoutConfigID: 2,
  LayoutConfigName: 'Hồ sơ',
  SubsystemCode: 'Employee',
  TableName: 'dbo_employee',
  ConfigSortOrder: null,
  GroupConfigParentID: 11513,
  SortOrder: 1,
  GroupType: 1,
  IsShowTooltip: false,
  Tooltip: null,
  Tooltip_EN: '',
  IsVisible: true,
  IsViewWhenAdd: true,
  ColumnGroup: 2,
  IsSystem: false,
  IsExpand: true,
  IsTypeForm: true,
  SubsystemCodeGroup: null,
  ConfigCloneDataMaster: null,
  APIConfig: null,
  CustomConfig: '{"IsVerticalTab": true}',
  DataGroupConfig: null,
  GroupFieldConfigs: [
    {
      ID: null,
      GroupFieldConfigID: 117116,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 0,
      ColumnIndex: 0,
      FieldName: 'Avatar2x3',
      DisplayField: null,
      Caption: 'Ảnh nhân viên (cỡ 2x3)',
      Caption_EN: 'Avatar (size 2x3)',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 0,
      TypeControl: 0,
      TypeConfig: null,
      IsRequire: false,
      IsVisible: false,
      IsReadOnly: null,
      Tooltip: null,
      Tooltip_EN: null,
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig: null,
      IsUnique: false,
      DefaultValue: null,
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: null,
      ControllerService: null,
      FieldNameSource: null,
      DisplayFieldSource: null,
      DataFieldSource: null,
      SortOrder: 0,
      IsUse: false,
      IsImport: false,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117117,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 0,
      ColumnIndex: 0,
      FieldName: 'Avatar3x4',
      DisplayField: null,
      Caption: 'Ảnh nhân viên (cỡ 3x4)',
      Caption_EN: 'Avatar (size 3x4)',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 0,
      TypeControl: 0,
      TypeConfig: null,
      IsRequire: false,
      IsVisible: false,
      IsReadOnly: null,
      Tooltip: null,
      Tooltip_EN: null,
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig: null,
      IsUnique: false,
      DefaultValue: null,
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: null,
      ControllerService: null,
      FieldNameSource: null,
      DisplayFieldSource: null,
      DataFieldSource: null,
      SortOrder: 0,
      IsUse: false,
      IsImport: false,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117118,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 0,
      ColumnIndex: 0,
      FieldName: 'Avatar4x6',
      DisplayField: null,
      Caption: 'Ảnh nhân viên (cỡ 4x6)',
      Caption_EN: 'Avatar (size 4x6)',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 0,
      TypeControl: 0,
      TypeConfig: null,
      IsRequire: false,
      IsVisible: false,
      IsReadOnly: null,
      Tooltip: null,
      Tooltip_EN: null,
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig: null,
      IsUnique: false,
      DefaultValue: null,
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: null,
      ControllerService: null,
      FieldNameSource: null,
      DisplayFieldSource: null,
      DataFieldSource: null,
      SortOrder: 0,
      IsUse: false,
      IsImport: false,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117119,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 0,
      ColumnIndex: 0,
      FieldName: 'Avatar6x9',
      DisplayField: null,
      Caption: 'Ảnh nhân viên (cỡ 6x9)',
      Caption_EN: 'Avatar (size 6x9)',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 0,
      TypeControl: 0,
      TypeConfig: null,
      IsRequire: false,
      IsVisible: false,
      IsReadOnly: null,
      Tooltip: null,
      Tooltip_EN: null,
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig: null,
      IsUnique: false,
      DefaultValue: null,
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: null,
      ControllerService: null,
      FieldNameSource: null,
      DisplayFieldSource: null,
      DataFieldSource: null,
      SortOrder: 1,
      IsUse: false,
      IsImport: false,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117120,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 0,
      ColumnIndex: 0,
      FieldName: 'VocativeAC',
      DisplayField: null,
      Caption: 'Xưng hô (Anh/Chị)',
      Caption_EN: 'Title (Mr./Ms.)',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 0,
      TypeControl: 0,
      TypeConfig: null,
      IsRequire: false,
      IsVisible: false,
      IsReadOnly: true,
      Tooltip: '',
      Tooltip_EN: 'Title (Mr./Ms.)',
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig: '{"IsMergeEN": true, "Maxlength": 30}',
      IsUnique: false,
      DefaultValue: null,
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: null,
      ControllerService: null,
      FieldNameSource: null,
      DisplayFieldSource: null,
      DataFieldSource: null,
      SortOrder: 0,
      IsUse: false,
      IsImport: false,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117121,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 0,
      ColumnIndex: 0,
      FieldName: 'VocativeOB',
      DisplayField: null,
      Caption: 'Xưng hô (Ông/Bà)',
      Caption_EN: 'Title (Mr./Mrs.)',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 0,
      TypeControl: 0,
      TypeConfig: null,
      IsRequire: false,
      IsVisible: false,
      IsReadOnly: true,
      Tooltip: '',
      Tooltip_EN: 'Title (Mr./Mrs.)',
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig: '{"IsMergeEN": true, "Maxlength": 30}',
      IsUnique: false,
      DefaultValue: null,
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: null,
      ControllerService: null,
      FieldNameSource: null,
      DisplayFieldSource: null,
      DataFieldSource: null,
      SortOrder: 0,
      IsUse: false,
      IsImport: false,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117100,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 1,
      ColumnIndex: 1,
      FieldName: 'EmployeeCode',
      DisplayField: null,
      Caption: 'Mã nhân viên',
      Caption_EN: 'Employee code',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 0,
      TypeControl: 9,
      TypeConfig: '3',
      IsRequire: true,
      IsVisible: true,
      IsReadOnly: null,
      Tooltip: 'Mã nhân viên',
      Tooltip_EN: 'Employee ID',
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig: '{"Maxlength": 50, "IsAutoCode": true}',
      IsUnique: true,
      DefaultValue: null,
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: null,
      ControllerService: null,
      FieldNameSource: null,
      DisplayFieldSource: null,
      DataFieldSource: null,
      SortOrder: 1,
      IsUse: true,
      IsImport: true,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: 'WHD2-DD1',
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117122,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 1,
      ColumnIndex: 1,
      FieldName: 'UserID',
      DisplayField: null,
      Caption: 'Ảnh đại diện',
      Caption_EN: 'Creator',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 0,
      TypeControl: 0,
      TypeConfig: null,
      IsRequire: false,
      IsVisible: false,
      IsReadOnly: null,
      Tooltip: 'Ảnh đại diện',
      Tooltip_EN: 'Creator',
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig: null,
      IsUnique: false,
      DefaultValue: null,
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: null,
      ControllerService: null,
      FieldNameSource: null,
      DisplayFieldSource: null,
      DataFieldSource: null,
      SortOrder: null,
      IsUse: false,
      IsImport: false,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117101,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 2,
      ColumnIndex: 1,
      FieldName: 'FirstName',
      DisplayField: null,
      Caption: 'Họ và đệm',
      Caption_EN: 'Last and middle name',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 0,
      TypeControl: 0,
      TypeConfig: null,
      IsRequire: false,
      IsVisible: true,
      IsReadOnly: null,
      Tooltip: 'Họ và đệm',
      Tooltip_EN: 'Last and middle name',
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig: '{"IsMergeEN": true, "Maxlength": 150}',
      IsUnique: false,
      DefaultValue: null,
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: null,
      ControllerService: null,
      FieldNameSource: null,
      DisplayFieldSource: null,
      DataFieldSource: null,
      SortOrder: 1,
      IsUse: true,
      IsImport: false,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117108,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 3,
      ColumnIndex: 1,
      FieldName: 'HomeLand',
      DisplayField: null,
      Caption: 'Nguyên quán',
      Caption_EN: 'Hometown',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 0,
      TypeControl: 0,
      TypeConfig: '2,3,4',
      IsRequire: false,
      IsVisible: true,
      IsReadOnly: null,
      Tooltip: 'Nguyên quán',
      Tooltip_EN: 'Hometown',
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig: '{"Maxlength": 255}',
      IsUnique: false,
      DefaultValue: null,
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: null,
      ControllerService: null,
      FieldNameSource: null,
      DisplayFieldSource: null,
      DataFieldSource: null,
      SortOrder: 14,
      IsUse: true,
      IsImport: true,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117102,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 4,
      ColumnIndex: 1,
      FieldName: 'LastName',
      DisplayField: null,
      Caption: 'Tên',
      Caption_EN: 'Name',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 0,
      TypeControl: 0,
      TypeConfig: null,
      IsRequire: false,
      IsVisible: true,
      IsReadOnly: null,
      Tooltip: 'Tên',
      Tooltip_EN: 'Name',
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig: '{"IsMergeEN": true, "Maxlength": 100}',
      IsUnique: false,
      DefaultValue: null,
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: null,
      ControllerService: null,
      FieldNameSource: null,
      DisplayFieldSource: null,
      DataFieldSource: null,
      SortOrder: 2,
      IsUse: true,
      IsImport: false,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117103,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 5,
      ColumnIndex: 1,
      FieldName: 'FullName',
      DisplayField: null,
      Caption: 'Họ và tên',
      Caption_EN: 'Full name',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 0,
      TypeControl: 17,
      TypeConfig: '3',
      IsRequire: true,
      IsVisible: true,
      IsReadOnly: true,
      Tooltip: 'Họ và Tên',
      Tooltip_EN: 'Full name',
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig:
        '{"IsMergeEN": true, "Maxlength": 255, "FormulaConfig": {"Type": 1, "Content": "${FirstName} + \' \' +${LastName}"}}',
      IsUnique: false,
      DefaultValue: null,
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: null,
      ControllerService: null,
      FieldNameSource: null,
      DisplayFieldSource: null,
      DataFieldSource: null,
      SortOrder: 2,
      IsUse: true,
      IsImport: true,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117105,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 6,
      ColumnIndex: 1,
      FieldName: 'GenderID',
      DisplayField: 'GenderName',
      Caption: 'Giới tính',
      Caption_EN: 'Sex',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 8,
      TypeControl: 3,
      TypeConfig: '1,2,3,4',
      IsRequire: false,
      IsVisible: true,
      IsReadOnly: null,
      Tooltip: 'Giới tính',
      Tooltip_EN: 'Sex',
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig: '{"IsMergeEN": true, "Maxlength": 15}',
      IsUnique: false,
      DefaultValue: null,
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: 'em_pick_list',
      ControllerService: null,
      FieldNameSource: 'PickListID',
      DisplayFieldSource: 'PickListValue',
      DataFieldSource: null,
      SortOrder: 3,
      IsUse: true,
      IsImport: true,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117107,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 7,
      ColumnIndex: 1,
      FieldName: 'BirthPlace',
      DisplayField: null,
      Caption: 'Nơi sinh',
      Caption_EN: 'Birthplace',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 0,
      TypeControl: 0,
      TypeConfig: '2,3,4',
      IsRequire: false,
      IsVisible: true,
      IsReadOnly: null,
      Tooltip: 'Nơi sinh',
      Tooltip_EN: 'Birthplace',
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig: '{"Maxlength": 255}',
      IsUnique: false,
      DefaultValue: null,
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: null,
      ControllerService: null,
      FieldNameSource: null,
      DisplayFieldSource: null,
      DataFieldSource: null,
      SortOrder: 14,
      IsUse: true,
      IsImport: true,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117142,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 2,
      ColumnIndex: 2,
      FieldName: 'GFN0000151CustomEmployee',
      DisplayField: null,
      Caption: 'hhh',
      Caption_EN: null,
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 0,
      TypeControl: 1,
      TypeConfig: '1,2,3',
      IsRequire: false,
      IsVisible: true,
      IsReadOnly: false,
      Tooltip: 'hhh',
      Tooltip_EN: null,
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig: null,
      IsUnique: false,
      DefaultValue: null,
      IsCustom: true,
      TableName: 'dbo_employee',
      TableNameSource: null,
      ControllerService: null,
      FieldNameSource: null,
      DisplayFieldSource: null,
      DataFieldSource: null,
      SortOrder: 9490,
      IsUse: false,
      IsImport: true,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117109,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 3,
      ColumnIndex: 2,
      FieldName: 'MaritalStatusID',
      DisplayField: 'MaritalStatusName',
      Caption: 'Tình trạng hôn nhân',
      Caption_EN: 'Marital status',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 8,
      TypeControl: 3,
      TypeConfig: '1,2,3,4',
      IsRequire: false,
      IsVisible: true,
      IsReadOnly: null,
      Tooltip: 'Tình trạng hôn nhân',
      Tooltip_EN: 'Marital status',
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig:
        '{"IsMergeEN": true, "Maxlength": 255, "PopupType": 4, "IsDynamicCombobox": true}',
      IsUnique: false,
      DefaultValue: null,
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: 'em_pick_list',
      ControllerService: null,
      FieldNameSource: 'PickListID',
      DisplayFieldSource: 'PickListValue',
      DataFieldSource: null,
      SortOrder: 15,
      IsUse: true,
      IsImport: true,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117110,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 4,
      ColumnIndex: 2,
      FieldName: 'PersonalTaxCode',
      DisplayField: null,
      Caption: 'MST cá nhân',
      Caption_EN: 'PIT code',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 0,
      TypeControl: 0,
      TypeConfig: '2,3',
      IsRequire: false,
      IsVisible: true,
      IsReadOnly: null,
      Tooltip: 'Mã số thuế cá nhân',
      Tooltip_EN: 'PIT code',
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig: '{"Maxlength": 20, "WarningCode": ["DulicateData"]}',
      IsUnique: true,
      DefaultValue: null,
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: null,
      ControllerService: null,
      FieldNameSource: null,
      DisplayFieldSource: null,
      DataFieldSource: null,
      SortOrder: 16,
      IsUse: true,
      IsImport: true,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117112,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 5,
      ColumnIndex: 2,
      FieldName: 'PersonalClassBackgroundID',
      DisplayField: 'PersonalClassBackgroundName',
      Caption: 'TP bản thân',
      Caption_EN: 'Personal status',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 8,
      TypeControl: 3,
      TypeConfig: '1,2,3,4',
      IsRequire: false,
      IsVisible: true,
      IsReadOnly: null,
      Tooltip: 'Thành phân bản thân',
      Tooltip_EN: 'Personal status',
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig:
        '{"IsMergeEN": true, "Maxlength": 255, "PopupType": 4, "IsDynamicCombobox": true}',
      IsUnique: false,
      DefaultValue: null,
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: 'em_pick_list',
      ControllerService: null,
      FieldNameSource: 'PickListID',
      DisplayFieldSource: 'PickListValue',
      DataFieldSource: null,
      SortOrder: 18,
      IsUse: true,
      IsImport: true,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117113,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 6,
      ColumnIndex: 2,
      FieldName: 'EthnicID',
      DisplayField: 'EthnicName',
      Caption: 'Dân tộc',
      Caption_EN: 'Ethnic group',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 8,
      TypeControl: 3,
      TypeConfig: '1,2,3,4',
      IsRequire: false,
      IsVisible: true,
      IsReadOnly: null,
      Tooltip: 'Dân tộc',
      Tooltip_EN: 'Ethnic group',
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig: '{"Maxlength": 255}',
      IsUnique: false,
      DefaultValue: '{"EthnicID": 1, "EthnicName": "Kinh"}',
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: 'em_pick_list',
      ControllerService: null,
      FieldNameSource: 'PickListID',
      DisplayFieldSource: 'PickListValue',
      DataFieldSource: null,
      SortOrder: 19,
      IsUse: true,
      IsImport: true,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117114,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 7,
      ColumnIndex: 2,
      FieldName: 'ReligionID',
      DisplayField: 'ReligionName',
      Caption: 'Tôn giáo',
      Caption_EN: 'Religion',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 8,
      TypeControl: 3,
      TypeConfig: '1,2,3,4',
      IsRequire: false,
      IsVisible: true,
      IsReadOnly: null,
      Tooltip: 'Tôn giáo',
      Tooltip_EN: 'Religion',
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig:
        '{"IsMergeEN": true, "Maxlength": 255, "PopupType": 4, "IsDynamicCombobox": true}',
      IsUnique: false,
      DefaultValue: '{"ReligionID": 1, "ReligionName": "Không"}',
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: 'em_pick_list',
      ControllerService: null,
      FieldNameSource: 'PickListID',
      DisplayFieldSource: 'PickListValue',
      DataFieldSource: null,
      SortOrder: 20,
      IsUse: true,
      IsImport: true,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117111,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 8,
      ColumnIndex: 2,
      FieldName: 'FamilyClassBackgroundID',
      DisplayField: 'FamilyClassBackgroundName',
      Caption: 'TP gia đình',
      Caption_EN: 'Family status',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 8,
      TypeControl: 3,
      TypeConfig: '1,2,3,4',
      IsRequire: false,
      IsVisible: true,
      IsReadOnly: null,
      Tooltip: 'Thành phần gia đình',
      Tooltip_EN: 'Family status',
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig:
        '{"IsMergeEN": true, "Maxlength": 255, "PopupType": 4, "IsDynamicCombobox": true}',
      IsUnique: false,
      DefaultValue: null,
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: 'em_pick_list',
      ControllerService: null,
      FieldNameSource: 'PickListID',
      DisplayFieldSource: 'PickListValue',
      DataFieldSource: null,
      SortOrder: 17,
      IsUse: true,
      IsImport: true,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117104,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 8,
      ColumnIndex: 2,
      FieldName: 'OtherName',
      DisplayField: null,
      Caption: 'Tên gọi khác',
      Caption_EN: 'Other name',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 0,
      TypeControl: 0,
      TypeConfig: '2,3',
      IsRequire: false,
      IsVisible: true,
      IsReadOnly: false,
      Tooltip: '',
      Tooltip_EN: 'Other name',
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig: null,
      IsUnique: false,
      DefaultValue: null,
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: null,
      ControllerService: null,
      FieldNameSource: null,
      DisplayFieldSource: null,
      DataFieldSource: null,
      SortOrder: 300,
      IsUse: true,
      IsImport: true,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117106,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 9,
      ColumnIndex: 2,
      FieldName: 'BirthDay',
      DisplayField: null,
      Caption: 'Ngày sinh',
      Caption_EN: 'Date of birth ',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 6,
      TypeControl: 5,
      TypeConfig: '2,3,4',
      IsRequire: false,
      IsVisible: true,
      IsReadOnly: null,
      Tooltip: 'Ngày sinh',
      Tooltip_EN: 'Date of birth',
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig: '{"IsMergeEN": true}',
      IsUnique: false,
      DefaultValue: null,
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: null,
      ControllerService: null,
      FieldNameSource: null,
      DisplayFieldSource: null,
      DataFieldSource: null,
      SortOrder: 4,
      IsUse: true,
      IsImport: true,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 117115,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 9,
      ColumnIndex: 2,
      FieldName: 'NationalityID',
      DisplayField: 'NationalityName',
      Caption: 'Quốc tịch',
      Caption_EN: 'Nationality',
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 0,
      TypeControl: 3,
      TypeConfig: '1,2,3,4',
      IsRequire: false,
      IsVisible: true,
      IsReadOnly: null,
      Tooltip: 'Quốc gia',
      Tooltip_EN: 'Nationality',
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig:
        '{"CacheName": "Nation", "IsMergeEN": true, "Maxlength": 255, "IsTranslateAddress": true}',
      IsUnique: false,
      DefaultValue: '{"NationalityID": "VN", "NationalityName": "Việt Nam"}',
      IsCustom: false,
      TableName: 'dbo_employee',
      TableNameSource: null,
      ControllerService: null,
      FieldNameSource: 'LocationID',
      DisplayFieldSource: 'LocationName',
      DataFieldSource: null,
      SortOrder: 27,
      IsUse: true,
      IsImport: true,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
    {
      ID: null,
      GroupFieldConfigID: 118570,
      LayoutConfigID: 2,
      GroupConfigID: 11514,
      SubsystemCode: 'Employee',
      RowIndex: 10,
      ColumnIndex: 2,
      FieldName: 'GFN0000153CustomEmployee',
      DisplayField: null,
      Caption: 'Một dòng',
      Caption_EN: null,
      FullCaption: null,
      FullCaption_EN: null,
      DataType: 0,
      TypeControl: 1,
      TypeConfig: '1,2,3',
      IsRequire: false,
      IsVisible: true,
      IsReadOnly: false,
      Tooltip: 'Một dòng',
      Tooltip_EN: null,
      IsShowTooltip: false,
      IsSystem: false,
      CustomConfig: null,
      IsUnique: false,
      DefaultValue: null,
      IsCustom: true,
      TableName: 'dbo_employee',
      TableNameSource: null,
      ControllerService: null,
      FieldNameSource: null,
      DisplayFieldSource: null,
      DataFieldSource: null,
      SortOrder: 9550,
      IsUse: true,
      IsImport: true,
      PermissionConfig: null,
      TypeEditField: 0,
      ListFileTemp: null,
      Width: null,
      PassWarningCode: null,
      GroupConfigName: null,
      GroupConfigParentID: null,
      GroupConfigParentCode: null,
      MergeFieldConfig: null,
      MergeFieldConfigSortOrder: 0,
      Value: null,
      ValueText: null,
    },
  ],
  MappingConfigs: null,
  ListGroupConfigChild: null,
  FieldID: 'EmployeeID',
  DictionaryKey: 2,
  PermissionConfig: null,
  IsDisable: false,
  TypeEditGroup: 1,
  IsUse: true,
  IsCustom: false,
};
